"""Type stubs for discord.py (optional dependency, dynamic module)."""
from typing import Any

# discord.py is a dynamic library without type stubs.
# This file silences pyright import errors for optional discord dependency.

class Client:
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Intents:
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    all: "Intents"
    default: "Intents"

class CommandTree:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Message:
    def __getattr__(self, name: str) -> Any: ...

class Interaction:
    def __getattr__(self, name: str) -> Any: ...

class TextChannel: ...
class DMChannel: ...
class Thread: ...
class PartialMessageable: ...
class PartialMessage: ...
class AllowedMentions: ...
class File: ...
class Attachment: ...
class AppCommandError(Exception): ...

# Module-level exports
def __getattr__(name: str) -> Any: ...